[[Comment]]
== Comment

=== 댓글 작성
댓글을 작성한다.

게시물 아이디, 액세스 토큰과 함께 요청한다.

성공 시 201 created 상태코드와 리소스 생성 위치를 응답한다.

==== 성공
operation::comments/save[snippets='path-parameters,request-headers,request-fields,http-request,http-response']

==== 실패
===== 존재하지 않는 게시물
operation::comments/save/notfound[snippets='http-request,http-response']

=== 댓글 수정

==== 성공
operation::comments/update[snippets='path-parameters,request-headers,request-fields,http-request,http-response']

==== 실패
===== 존재하지 않는 댓글
operation::comments/update/notfound[snippets='http-request,http-response']

=== 댓글 조회
- 게시물 아이디, page, size, sort를 parameter 값으로 요청한다.
- page는 입력하지 않았을 때 0으로 적용된다.
- size는 입력하지 않았을 때 10으로 적용된다.
- sort를 입력하지 않았을 때 id 내림차순 정렬이 적용된다.

==== 성공
===== 데이터가 있는 경우
operation::comments/find[snippets='path-parameters,request-headers,response-fields,http-request,http-response']

===== 데이터가 없는 경우
operation::comments/find/empty[snippets='response-fields,http-request,http-response']

=== 댓글 삭제
댓글을 삭제한다.

게시물 아이디, 액세스 토큰과 함께 요청한다.

==== 성공
operation::comments/delete[snippets='path-parameters,request-headers,http-request,http-response']

==== 실패
===== 작성자가 아닌 경우
operation::comments/delete/badrequest[snippets='http-request,http-response']